# Readable ggplot2 code generated by policycraft
library(ggplot2)
library(dplyr)

chart_data <- data.frame(
  `date` = structure(c(9131, 9496, 9862, 10227, 10592, 10957, 11323, 11688,
12053, 12418, 12784, 13149, 13514, 13879, 14245, 14610, 14975,
15340, 15706, 16071, 16436, 16801, 17167, 17532, 17897, 18628,
18993, 19358, 19723, 20089, 20454), class = "Date"),
  `value` = c(0.647, 0.72, 0.806, 0.858, 0.855, 0.907, 0.927, 0.952, 0.835,
0.85, 0.8, 0.83, 0.85, 0.87, 0.87, 0.88, 0.88, 0.802848575712144,
0.761141712568853, 0.782622950819672, 0.837923171373443, 0.809057913839356,
0.811295582567447, 0.827356634891814, 0.819062544522012, 0.758702665987434,
0.753041910770617, 0.77009520836585, 0.712910986367281, 0.719685812469318,
0.690723375753516),
  `Year` = c(1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004,
2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015,
2016, 2017, 2018, 2019, 2021, 2022, 2023, 2024, 2025, 2026),
  `academic_year` = c("1994-1995", "1995-1996", "1996-1997", "1997-1998", "1998-1999",
"1999-2000", "2000-2001", "2001-2002", "2002-2003", "2003-2004",
"2004-2005", "2005-2006", "2006-2007", "2007-2008", "2008-2009",
"2009-2010", "2010-2011", "2011-2012", "2012-2013", "2013-2014",
"2014-2015", "2015-2016", "2016-2017", "2017-2018", "2018-2019",
"2020-2021", "2021-2022", "2022-2023", "2023-2024", "2024-2025",
"2025-2026"),
  `percent` = c(64.7, 72, 80.6, 85.8, 85.5, 90.7, 92.7, 95.2, 83.5, 85, 80,
83, 85, 87, 87, 88, 88, 80.2848575712144, 76.1141712568853, 78.2622950819672,
83.7923171373443, 80.9057913839356, 81.1295582567447, 82.7356634891814,
81.9062544522012, 75.8702665987434, 75.3041910770617, 77.009520836585,
71.2910986367282, 71.9685812469318, 69.0723375753516),
  `series_label` = c("Mathematics", "Mathematics", "Mathematics", "Mathematics",
"Mathematics", "Mathematics", "Mathematics", "Mathematics", "Mathematics",
"Mathematics", "Mathematics", "Mathematics", "Mathematics", "Mathematics",
"Mathematics", "Mathematics", "Mathematics", "Mathematics", "Mathematics",
"Mathematics", "Mathematics", "Mathematics", "Mathematics", "Mathematics",
"Mathematics", "Mathematics", "Mathematics", "Mathematics", "Mathematics",
"Mathematics", "Mathematics"),
  `subject` = c("Mathematics", "Mathematics", "Mathematics", "Mathematics",
"Mathematics", "Mathematics", "Mathematics", "Mathematics", "Mathematics",
"Mathematics", "Mathematics", "Mathematics", "Mathematics", "Mathematics",
"Mathematics", "Mathematics", "Mathematics", "Mathematics", "Mathematics",
"Mathematics", "Mathematics", "Mathematics", "Mathematics", "Mathematics",
"Mathematics", "Mathematics", "Mathematics", "Mathematics", "Mathematics",
"Mathematics", "Mathematics"),
  `subject_sort` = c(3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3),
  `exam_type` = c("TAAS", "TAAS", "TAAS", "TAAS", "TAAS", "TAAS", "TAAS", "TAAS",
"TAKS", "TAKS", "TAKS", "TAKS", "TAKS", "TAKS", "TAKS", "TAKS",
"TAKS", "STAAR", "STAAR", "STAAR", "STAAR", "STAAR", "STAAR",
"STAAR", "STAAR", "STAAR", "STAAR", "STAAR", "STAAR", "STAAR",
"STAAR"),
  `exam_name` = c("Texas Assessment of Academic Skills", "Texas Assessment of Academic Skills",
"Texas Assessment of Academic Skills", "Texas Assessment of Academic Skills",
"Texas Assessment of Academic Skills", "Texas Assessment of Academic Skills",
"Texas Assessment of Academic Skills", "Texas Assessment of Academic Skills",
"Texas Assessment of Knowledge and Skills", "Texas Assessment of Knowledge and Skills",
"Texas Assessment of Knowledge and Skills", "Texas Assessment of Knowledge and Skills",
"Texas Assessment of Knowledge and Skills", "Texas Assessment of Knowledge and Skills",
"Texas Assessment of Knowledge and Skills", "Texas Assessment of Knowledge and Skills",
"Texas Assessment of Knowledge and Skills", "State of Texas Assessments of Academic Readiness",
"State of Texas Assessments of Academic Readiness", "State of Texas Assessments of Academic Readiness",
"State of Texas Assessments of Academic Readiness", "State of Texas Assessments of Academic Readiness",
"State of Texas Assessments of Academic Readiness", "State of Texas Assessments of Academic Readiness",
"State of Texas Assessments of Academic Readiness", "State of Texas Assessments of Academic Readiness",
"State of Texas Assessments of Academic Readiness", "State of Texas Assessments of Academic Readiness",
"State of Texas Assessments of Academic Readiness", "State of Texas Assessments of Academic Readiness",
"State of Texas Assessments of Academic Readiness"),
  `exam_sort` = c(1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3,
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3),
  `performance_standard` = c("Met standard or above (source-harmonized)", "Met standard or above (source-harmonized)",
"Met standard or above (source-harmonized)", "Met standard or above (source-harmonized)",
"Met standard or above (source-harmonized)", "Met standard or above (source-harmonized)",
"Met standard or above (source-harmonized)", "Met standard or above (source-harmonized)",
"Met standard or above (source-harmonized)", "Met standard or above (source-harmonized)",
"Met standard or above (source-harmonized)", "Met standard or above (source-harmonized)",
"Met standard or above (source-harmonized)", "Met standard or above (source-harmonized)",
"Met standard or above (source-harmonized)", "Met standard or above (source-harmonized)",
"Met standard or above (source-harmonized)", "Satisfactory",
"Satisfactory", "Satisfactory", "Satisfactory", "Satisfactory",
"Approaches and Above", "Approaches and Above", "Approaches and Above",
"Approaches and Above", "Approaches and Above", "Approaches and Above",
"Approaches and Above", "Approaches and Above", "Approaches and Above"
),
  `tests_passed` = c(NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
NA, NA, 4284, 4560, 4774, 4777, 5127, 5473, 5468, 5749, 4468,
5013, 4934, 4445, 4398, 4125),
  `tests_taken` = c(NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
NA, NA, 5336, 5991, 6100, 5701, 6337, 6746, 6609, 7019, 5889,
6657, 6407, 6235, 6111, 5972),
  `grades_included` = c("District-reported tested grades", "District-reported tested grades",
"District-reported tested grades", "District-reported tested grades",
"District-reported tested grades", "District-reported tested grades",
"District-reported tested grades", "District-reported tested grades",
"District-reported tested grades", "District-reported tested grades",
"District-reported tested grades", "District-reported tested grades",
"District-reported tested grades", "District-reported tested grades",
"District-reported tested grades", "District-reported tested grades",
"District-reported tested grades", "3,4,5,6,7,8", "3,4,5,6,7,8",
"3,4,5,6,7,8", "3,4,5,6,7,8", "3,4,5,6,7,8", "3,4,5,6,7,8", "3,4,5,6,7,8",
"3,4,5,6,7,8", "3,4,5,6,7,8", "3,4,5,6,7,8", "3,4,5,6,7,8", "3,4,5,6,7,8",
"3,4,5,6,7,8", "3,4,5,6,7,8"),
  `grade_count` = c(NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
NA, NA, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6),
  `calculation_method` = c("reported_district_subject_proportion", "reported_district_subject_proportion",
"reported_district_subject_proportion", "reported_district_subject_proportion",
"reported_district_subject_proportion", "reported_district_subject_proportion",
"reported_district_subject_proportion", "reported_district_subject_proportion",
"reported_district_subject_proportion", "reported_district_subject_proportion",
"reported_district_subject_proportion", "reported_district_subject_proportion",
"reported_district_subject_proportion", "reported_district_subject_proportion",
"reported_district_subject_proportion", "reported_district_subject_proportion",
"reported_district_subject_proportion", "ratio_of_sums_tests_passed_divided_by_tests_taken",
"ratio_of_sums_tests_passed_divided_by_tests_taken", "ratio_of_sums_tests_passed_divided_by_tests_taken",
"ratio_of_sums_tests_passed_divided_by_tests_taken", "ratio_of_sums_tests_passed_divided_by_tests_taken",
"ratio_of_sums_tests_passed_divided_by_tests_taken", "ratio_of_sums_tests_passed_divided_by_tests_taken",
"ratio_of_sums_tests_passed_divided_by_tests_taken", "ratio_of_sums_tests_passed_divided_by_tests_taken",
"ratio_of_sums_tests_passed_divided_by_tests_taken", "ratio_of_sums_tests_passed_divided_by_tests_taken",
"ratio_of_sums_tests_passed_divided_by_tests_taken", "ratio_of_sums_tests_passed_divided_by_tests_taken",
"ratio_of_sums_tests_passed_divided_by_tests_taken"),
  `series_type` = c("reported", "reported", "reported", "reported", "reported",
"reported", "reported", "reported", "reported", "reported", "reported",
"reported", "reported", "reported", "reported", "reported", "reported",
"derived_from_counts", "derived_from_counts", "derived_from_counts",
"derived_from_counts", "derived_from_counts", "derived_from_counts",
"derived_from_counts", "derived_from_counts", "derived_from_counts",
"derived_from_counts", "derived_from_counts", "derived_from_counts",
"derived_from_counts", "derived_from_counts"),
  `reporting_status` = c("reported", "reported", "reported", "reported", "reported",
"reported", "reported", "reported", "reported", "reported", "reported",
"reported", "reported", "reported", "reported", "reported", "reported",
"reported_or_derived", "reported_or_derived", "reported_or_derived",
"reported_or_derived", "reported_or_derived", "reported_or_derived",
"reported_or_derived", "reported_or_derived", "reported_or_derived",
"reported_or_derived", "reported_or_derived", "reported_or_derived",
"reported_or_derived", "reported_or_derived"),
  `unit` = c("proportion", "proportion", "proportion", "proportion", "proportion",
"proportion", "proportion", "proportion", "proportion", "proportion",
"proportion", "proportion", "proportion", "proportion", "proportion",
"proportion", "proportion", "proportion", "proportion", "proportion",
"proportion", "proportion", "proportion", "proportion", "proportion",
"proportion", "proportion", "proportion", "proportion", "proportion",
"proportion"),
  `direction` = c("higher_is_better", "higher_is_better", "higher_is_better",
"higher_is_better", "higher_is_better", "higher_is_better", "higher_is_better",
"higher_is_better", "higher_is_better", "higher_is_better", "higher_is_better",
"higher_is_better", "higher_is_better", "higher_is_better", "higher_is_better",
"higher_is_better", "higher_is_better", "higher_is_better", "higher_is_better",
"higher_is_better", "higher_is_better", "higher_is_better", "higher_is_better",
"higher_is_better", "higher_is_better", "higher_is_better", "higher_is_better",
"higher_is_better", "higher_is_better", "higher_is_better", "higher_is_better"
),
  `district_id` = c("094902", "094902", "094902", "094902", "094902", "094902",
"094902", "094902", "094902", "094902", "094902", "094902", "094902",
"094902", "094902", "094902", "094902", "094902", "094902", "094902",
"094902", "094902", "094902", "094902", "094902", "094902", "094902",
"094902", "094902", "094902", "094902"),
  `organization_name` = c("Schertz-Cibolo-Universal City ISD", "Schertz-Cibolo-Universal City ISD",
"Schertz-Cibolo-Universal City ISD", "Schertz-Cibolo-Universal City ISD",
"Schertz-Cibolo-Universal City ISD", "Schertz-Cibolo-Universal City ISD",
"Schertz-Cibolo-Universal City ISD", "Schertz-Cibolo-Universal City ISD",
"Schertz-Cibolo-Universal City ISD", "Schertz-Cibolo-Universal City ISD",
"Schertz-Cibolo-Universal City ISD", "Schertz-Cibolo-Universal City ISD",
"Schertz-Cibolo-Universal City ISD", "Schertz-Cibolo-Universal City ISD",
"Schertz-Cibolo-Universal City ISD", "Schertz-Cibolo-Universal City ISD",
"Schertz-Cibolo-Universal City ISD", "Schertz-Cibolo-Universal City ISD",
"Schertz-Cibolo-Universal City ISD", "Schertz-Cibolo-Universal City ISD",
"Schertz-Cibolo-Universal City ISD", "Schertz-Cibolo-Universal City ISD",
"Schertz-Cibolo-Universal City ISD", "Schertz-Cibolo-Universal City ISD",
"Schertz-Cibolo-Universal City ISD", "Schertz-Cibolo-Universal City ISD",
"Schertz-Cibolo-Universal City ISD", "Schertz-Cibolo-Universal City ISD",
"Schertz-Cibolo-Universal City ISD", "Schertz-Cibolo-Universal City ISD",
"Schertz-Cibolo-Universal City ISD"),
  `source_file` = c("SCUC_Snapshots_1995_to_2023_LONG_CANONICAL.csv", "SCUC_Snapshots_1995_to_2023_LONG_CANONICAL.csv",
"SCUC_Snapshots_1995_to_2023_LONG_CANONICAL.csv", "SCUC_Snapshots_1995_to_2023_LONG_CANONICAL.csv",
"SCUC_Snapshots_1995_to_2023_LONG_CANONICAL.csv", "SCUC_Snapshots_1995_to_2023_LONG_CANONICAL.csv",
"SCUC_Snapshots_1995_to_2023_LONG_CANONICAL.csv", "SCUC_Snapshots_1995_to_2023_LONG_CANONICAL.csv",
"SCUC_Snapshots_1995_to_2023_LONG_CANONICAL.csv", "SCUC_Snapshots_1995_to_2023_LONG_CANONICAL.csv",
"SCUC_Snapshots_1995_to_2023_LONG_CANONICAL.csv", "SCUC_Snapshots_1995_to_2023_LONG_CANONICAL.csv",
"SCUC_Snapshots_1995_to_2023_LONG_CANONICAL.csv", "SCUC_Snapshots_1995_to_2023_LONG_CANONICAL.csv",
"SCUC_Snapshots_1995_to_2023_LONG_CANONICAL.csv", "SCUC_Snapshots_1995_to_2023_LONG_CANONICAL.csv",
"SCUC_Snapshots_1995_to_2023_LONG_CANONICAL.csv", "SCUC_STAAR_Grades_3_8_Annual_2012_2026_LONG_CANONICAL.csv",
"SCUC_STAAR_Grades_3_8_Annual_2012_2026_LONG_CANONICAL.csv",
"SCUC_STAAR_Grades_3_8_Annual_2012_2026_LONG_CANONICAL.csv",
"SCUC_STAAR_Grades_3_8_Annual_2012_2026_LONG_CANONICAL.csv",
"SCUC_STAAR_Grades_3_8_Annual_2012_2026_LONG_CANONICAL.csv",
"SCUC_STAAR_Grades_3_8_Annual_2012_2026_LONG_CANONICAL.csv",
"SCUC_STAAR_Grades_3_8_Annual_2012_2026_LONG_CANONICAL.csv",
"SCUC_STAAR_Grades_3_8_Annual_2012_2026_LONG_CANONICAL.csv",
"SCUC_STAAR_Grades_3_8_Annual_2012_2026_LONG_CANONICAL.csv",
"SCUC_STAAR_Grades_3_8_Annual_2012_2026_LONG_CANONICAL.csv",
"SCUC_STAAR_Grades_3_8_Annual_2012_2026_LONG_CANONICAL.csv",
"SCUC_STAAR_Grades_3_8_Annual_2012_2026_LONG_CANONICAL.csv",
"SCUC_STAAR_Grades_3_8_Annual_2012_2026_LONG_CANONICAL.csv",
"SCUC_STAAR_Grades_3_8_Annual_2012_2026_LONG_CANONICAL.csv"),
  `.plot_group` = structure(c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L,
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L,
1L, 1L), levels = "Mathematics", class = "factor"),
  `.chart_x` = structure(c(9131, 9496, 9862, 10227, 10592, 10957, 11323, 11688,
12053, 12418, 12784, 13149, 13514, 13879, 14245, 14610, 14975,
15340, 15706, 16071, 16436, 16801, 17167, 17532, 17897, 18628,
18993, 19358, 19723, 20089, 20454), class = "Date"),
  `emp_cl_orig` = c(0.836894225699, 0.836894225699, 0.836894225699, 0.836894225699,
0.836894225699, 0.836894225699, 0.836894225699, 0.836894225699,
0.836894225699, 0.836894225699, 0.836894225699, 0.836894225699,
0.836894225699, 0.836894225699, 0.836894225699, 0.836894225699,
0.836894225699, 0.836894225699, 0.836894225699, 0.836894225699,
0.836894225699, 0.836894225699, 0.836894225699, 0.836894225699,
0.836894225699, 0.836894225699, 0.836894225699, 0.836894225699,
0.836894225699, 0.836894225699, 0.836894225699),
  `emp_ucl_orig` = c(0.997110359051047, 0.997110359051047, 0.997110359051047, 0.997110359051047,
0.997110359051047, 0.997110359051047, 0.997110359051047, 0.997110359051047,
0.997110359051047, 0.997110359051047, 0.997110359051047, 0.997110359051047,
0.997110359051047, 0.997110359051047, 0.997110359051047, 0.997110359051047,
0.997110359051047, 0.997110359051047, 0.997110359051047, 0.997110359051047,
0.997110359051047, 0.997110359051047, 0.997110359051047, 0.997110359051047,
0.997110359051047, 0.997110359051047, 0.997110359051047, 0.997110359051047,
0.997110359051047, 0.997110359051047, 0.997110359051047),
  `emp_lcl_orig` = c(0.676678092346953, 0.676678092346953, 0.676678092346953, 0.676678092346953,
0.676678092346953, 0.676678092346953, 0.676678092346953, 0.676678092346953,
0.676678092346953, 0.676678092346953, 0.676678092346953, 0.676678092346953,
0.676678092346953, 0.676678092346953, 0.676678092346953, 0.676678092346953,
0.676678092346953, 0.676678092346953, 0.676678092346953, 0.676678092346953,
0.676678092346953, 0.676678092346953, 0.676678092346953, 0.676678092346953,
0.676678092346953, 0.676678092346953, 0.676678092346953, 0.676678092346953,
0.676678092346953, 0.676678092346953, 0.676678092346953),
  `emp_cl_recalc` = c(0.774373229810647, 0.774373229810647, 0.774373229810647, 0.774373229810647,
0.774373229810647, 0.774373229810647, 0.774373229810647, 0.774373229810647,
0.774373229810647, 0.774373229810647, 0.774373229810647, 0.774373229810647,
0.774373229810647, 0.774373229810647, 0.774373229810647, 0.774373229810647,
0.774373229810647, 0.774373229810647, 0.774373229810647, 0.774373229810647,
0.774373229810647, 0.774373229810647, 0.774373229810647, 0.774373229810647,
0.774373229810647, 0.774373229810647, 0.774373229810647, 0.774373229810647,
0.774373229810647, 0.774373229810647, 0.774373229810647),
  `emp_ucl_recalc` = c(0.883035295711498, 0.883035295711498, 0.883035295711498, 0.883035295711498,
0.883035295711498, 0.883035295711498, 0.883035295711498, 0.883035295711498,
0.883035295711498, 0.883035295711498, 0.883035295711498, 0.883035295711498,
0.883035295711498, 0.883035295711498, 0.883035295711498, 0.883035295711498,
0.883035295711498, 0.883035295711498, 0.883035295711498, 0.883035295711498,
0.883035295711498, 0.883035295711498, 0.883035295711498, 0.883035295711498,
0.883035295711498, 0.883035295711498, 0.883035295711498, 0.883035295711498,
0.883035295711498, 0.883035295711498, 0.883035295711498),
  `emp_lcl_recalc` = c(0.665711163909796, 0.665711163909796, 0.665711163909796, 0.665711163909796,
0.665711163909796, 0.665711163909796, 0.665711163909796, 0.665711163909796,
0.665711163909796, 0.665711163909796, 0.665711163909796, 0.665711163909796,
0.665711163909796, 0.665711163909796, 0.665711163909796, 0.665711163909796,
0.665711163909796, 0.665711163909796, 0.665711163909796, 0.665711163909796,
0.665711163909796, 0.665711163909796, 0.665711163909796, 0.665711163909796,
0.665711163909796, 0.665711163909796, 0.665711163909796, 0.665711163909796,
0.665711163909796, 0.665711163909796, 0.665711163909796),
  `recalc_date` = structure(c(15924, 15924, 15924, 15924, 15924, 15924, 15924,
15924, 15924, 15924, 15924, 15924, 15924, 15924, 15924, 15924,
15924, 15924, 15924, 15924, 15924, 15924, 15924, 15924, 15924,
15924, 15924, 15924, 15924, 15924, 15924), class = "Date"),
  `sigma_signals` = c(TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE,
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE,
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE,
FALSE, FALSE, FALSE, FALSE),
  `same_side_signal` = c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE,
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE,
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE,
FALSE, FALSE, FALSE, FALSE),
  `trend_signal` = c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE,
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE,
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE,
FALSE, FALSE, FALSE, FALSE),
  `alternating_signal` = c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE,
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE,
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE,
FALSE, FALSE, FALSE, FALSE),
  `runs_signal` = c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE,
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE,
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE,
FALSE, FALSE, FALSE, FALSE)
,
  check.names = FALSE
)

# The limit and signal columns below are the values calculated by Policycraft.
# Superintendent terms shown in the Policycraft app. The downloaded code omits
# these layers, so they are reproduced here for the annual series.
superintendent_terms <- data.frame(
  superintendent = c(
    "Dr. Byron P. Steele II",
    "Dr. Edward \"Ed\" West",
    "Dr. Greg Gibson",
    "Dr. Clark C. Ealy",
    "Mrs. Paige A. Meloni"
  ),
  term_label = c(
    "1976–2001", "2001–2009", "2010–2020", "2020–2024", "2024–Present"
  ),
  start = as.Date(c(
    "1976-01-01", "2001-01-01", "2010-01-01", "2020-01-01", "2024-01-01"
  )),
  end = as.Date(c(
    "2001-01-01", "2010-01-01", "2020-01-01", "2024-01-01", NA
  ))
)

visible_min <- min(chart_data$date, na.rm = TRUE)
visible_max <- as.Date(paste0(max(chart_data$Year, na.rm = TRUE), "-12-31"))
superintendent_terms$visible_start <- pmax(superintendent_terms$start, visible_min)
superintendent_terms$end[is.na(superintendent_terms$end)] <- visible_max
superintendent_terms$visible_end <- pmin(superintendent_terms$end, visible_max)
superintendent_terms <- superintendent_terms[
  superintendent_terms$visible_start <= superintendent_terms$visible_end,
]
superintendent_terms$midpoint <- superintendent_terms$visible_start +
  as.numeric(superintendent_terms$visible_end - superintendent_terms$visible_start) / 2
superintendent_terms$label <- paste0(
  superintendent_terms$superintendent, "\n", superintendent_terms$term_label
)
superintendent_terms$label_angle <- ifelse(
  as.numeric(superintendent_terms$visible_end - superintendent_terms$visible_start) <
    365.25 * 4,
  90,
  0
)
superintendent_terms$label_hjust <- ifelse(superintendent_terms$label_angle == 90, 1.05, 0.5)

line_end <- chart_data |>
  filter(!is.na(value)) |>
  slice_max(date, n = 1, with_ties = FALSE)

chart <- ggplot(chart_data, aes(x = `date`, y = value, group = `.plot_group`))
chart <- chart + geom_line(colour = "darkgray", linewidth = 1.2)
chart <- chart + geom_point(aes(colour = sigma_signals), size = 2.5)
chart <- chart + geom_text(
  data = line_end,
  aes(label = subject),
  colour = "darkgray",
  size = 5,
  fontface = "bold",
  hjust = -0.15,
  vjust = 0.5,
  inherit.aes = TRUE,
  show.legend = FALSE
)
chart <- chart + geom_line(aes(y = ifelse(`.chart_x` < recalc_date, emp_cl_orig, NA)), colour = "blue")
chart <- chart + geom_line(aes(y = ifelse(`.chart_x` >= recalc_date, emp_cl_recalc, NA)), colour = "green")
chart <- chart + geom_line(aes(y = ifelse(`.chart_x` < recalc_date, emp_ucl_orig, NA)), colour = "red")
chart <- chart + geom_line(aes(y = ifelse(`.chart_x` < recalc_date, emp_lcl_orig, NA)), colour = "red")
chart <- chart + geom_line(aes(y = ifelse(`.chart_x` >= recalc_date, emp_ucl_recalc, NA)), colour = "red", linetype = "dashed")
chart <- chart + geom_line(aes(y = ifelse(`.chart_x` >= recalc_date, emp_lcl_recalc, NA)), colour = "red", linetype = "dashed")
chart <- chart + geom_vline(xintercept = unique(chart_data$recalc_date), colour = "purple", linetype = "dotted")
chart <- chart + annotate("text", x = min(chart_data$`date`), y = chart_data$emp_cl_orig[1], label = paste0("Original CL (", round(chart_data$emp_cl_orig[1], 2), ")"), colour = "blue", size = 4.8, fontface = "bold", hjust = 0, vjust = -0.8)
chart <- chart + annotate("text", x = unique(chart_data$recalc_date), y = chart_data$emp_cl_recalc[1], label = paste0("Recalculated CL (", round(chart_data$emp_cl_recalc[1], 2), ")"), colour = "green4", size = 4.8, fontface = "bold", hjust = 0, vjust = -0.8)
chart <- chart + annotate("text", x = min(chart_data$`date`), y = chart_data$emp_ucl_orig[1], label = paste0("Original UCL (", round(chart_data$emp_ucl_orig[1], 2), ")"), colour = "red", size = 4.6, fontface = "bold", hjust = 0, vjust = -0.6)
chart <- chart + annotate("text", x = min(chart_data$`date`), y = chart_data$emp_lcl_orig[1], label = paste0("Original LCL (", round(chart_data$emp_lcl_orig[1], 2), ")"), colour = "red", size = 4.6, fontface = "bold", hjust = 0, vjust = 1.4)
chart <- chart + annotate("text", x = unique(chart_data$recalc_date), y = chart_data$emp_ucl_recalc[1], label = paste0("Recalculated UCL (", round(chart_data$emp_ucl_recalc[1], 2), ")"), colour = "red", size = 4.6, fontface = "bold", hjust = 0, vjust = -0.6)
chart <- chart + annotate("text", x = unique(chart_data$recalc_date), y = chart_data$emp_lcl_recalc[1], label = paste0("Recalculated LCL (", round(chart_data$emp_lcl_recalc[1], 2), ")"), colour = "red", size = 4.6, fontface = "bold", hjust = 0, vjust = 1.4)
chart <- chart + geom_segment(
  data = superintendent_terms,
  aes(x = visible_start, xend = visible_end, y = Inf, yend = Inf),
  inherit.aes = FALSE,
  colour = "#34495E",
  linewidth = 1.15,
  arrow = grid::arrow(
    angle = 25,
    length = grid::unit(0.14, "inches"),
    ends = "both",
    type = "closed"
  ),
  show.legend = FALSE
)
chart <- chart + geom_text(
  data = superintendent_terms,
  aes(
    x = midpoint,
    y = Inf,
    label = label,
    angle = label_angle,
    hjust = label_hjust
  ),
  inherit.aes = FALSE,
  colour = "#263746",
  size = 5,
  fontface = "bold",
  lineheight = 0.9,
  vjust = 1.75,
  check_overlap = FALSE,
  show.legend = FALSE
)
chart <- chart + scale_colour_manual(values = c(`TRUE` = "red", `FALSE` = "blue"))

# Match the graduations used in the Policycraft app.
date_span <- as.numeric(diff(range(chart_data$date, na.rm = TRUE)))
date_breaks <- if (date_span > 1825) "1 year" else if (date_span > 365) "6 months" else if (date_span > 90) "1 month" else "1 week"
date_labels <- if (all(format(chart_data$date, "%m-%d") == "01-01")) "%Y" else "%Y-%m-%d"
chart <- chart + scale_x_date(date_breaks = date_breaks, date_labels = date_labels, expand = expansion(mult = c(0.05, 0.18)))
chart <- chart + scale_y_continuous(labels = scales::label_percent(accuracy = 1))

chart <- chart + ggplot2::labs(
    title = "Title",
    subtitle = "Subtitle",
    caption = "Caption",
    x = "Academic Year Ended",
    y = "Pct Meeting Standard"
  )
chart <- chart + policycraft::policycraft_chart_theme()
chart <- chart + theme(
  axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank()
)

if (interactive()) print(chart)

# Save in a widescreen landscape layout. Keeping these dimensions here makes
# the intended orientation reproducible when this script is run directly.
ggsave(
  filename = "ggplot2 code/math_expectation_chart_2026-09-11-landscape.png",
  plot = chart,
  width = 16,
  height = 9,
  units = "in",
  dpi = 300,
  bg = "white"
)
