# Readable ggplot2 code generated by policycraft
library(ggplot2)
library(dplyr)
source(file.path("ggplot2 code", "did_it_work_chart_helpers.R"))

chart_data <- data.frame(
  `date` = structure(c(12053, 12418, 12784, 13149, 13514, 13879, 14245, 
14610, 14975, 15340, 15706, 16071, 16436, 16801, 17167, 17532, 
17897, 18628, 18993, 19358, 19723, 20089, 20454), class = "Date"),
  `value` = c(0.758, 0.83, 0.77, 0.83, 0.82, 0.82, 0.86, 0.88, 0.89, 0.821484992101106, 
0.829198473282443, 0.829119850187266, 0.772338403041825, 0.804327808471455, 
0.796678635547576, 0.793301013662406, 0.816977225672878, 0.780058651026393, 
0.782008368200837, 0.777059077188443, 0.717113946326441, 0.745969498910675, 
0.754856614246068),
  `Year` = c(2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 
2013, 2014, 2015, 2016, 2017, 2018, 2019, 2021, 2022, 2023, 2024, 
2025, 2026),
  `academic_year` = c("2002-2003", "2003-2004", "2004-2005", "2005-2006", "2006-2007", 
"2007-2008", "2008-2009", "2009-2010", "2010-2011", "2011-2012", 
"2012-2013", "2013-2014", "2014-2015", "2015-2016", "2016-2017", 
"2017-2018", "2018-2019", "2020-2021", "2021-2022", "2022-2023", 
"2023-2024", "2024-2025", "2025-2026"),
  `percent` = c(75.8, 83, 77, 83, 82, 82, 86, 88, 89, 82.1484992101106, 82.9198473282443, 
82.9119850187266, 77.2338403041825, 80.4327808471455, 79.6678635547576, 
79.3301013662406, 81.6977225672878, 78.0058651026393, 78.2008368200837, 
77.7059077188443, 71.7113946326441, 74.5969498910675, 75.4856614246068
),
  `series_label` = c("Science", "Science", "Science", "Science", "Science", "Science", 
"Science", "Science", "Science", "Science", "Science", "Science", 
"Science", "Science", "Science", "Science", "Science", "Science", 
"Science", "Science", "Science", "Science", "Science"),
  `subject` = c("Science", "Science", "Science", "Science", "Science", "Science", 
"Science", "Science", "Science", "Science", "Science", "Science", 
"Science", "Science", "Science", "Science", "Science", "Science", 
"Science", "Science", "Science", "Science", "Science"),
  `subject_sort` = c(4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
4, 4, 4),
  `exam_type` = c("TAKS", "TAKS", "TAKS", "TAKS", "TAKS", "TAKS", "TAKS", "TAKS", 
"TAKS", "STAAR", "STAAR", "STAAR", "STAAR", "STAAR", "STAAR", 
"STAAR", "STAAR", "STAAR", "STAAR", "STAAR", "STAAR", "STAAR", 
"STAAR"),
  `exam_name` = c("Texas Assessment of Knowledge and Skills", "Texas Assessment of Knowledge and Skills", 
"Texas Assessment of Knowledge and Skills", "Texas Assessment of Knowledge and Skills", 
"Texas Assessment of Knowledge and Skills", "Texas Assessment of Knowledge and Skills", 
"Texas Assessment of Knowledge and Skills", "Texas Assessment of Knowledge and Skills", 
"Texas Assessment of Knowledge and Skills", "State of Texas Assessments of Academic Readiness", 
"State of Texas Assessments of Academic Readiness", "State of Texas Assessments of Academic Readiness", 
"State of Texas Assessments of Academic Readiness", "State of Texas Assessments of Academic Readiness", 
"State of Texas Assessments of Academic Readiness", "State of Texas Assessments of Academic Readiness", 
"State of Texas Assessments of Academic Readiness", "State of Texas Assessments of Academic Readiness", 
"State of Texas Assessments of Academic Readiness", "State of Texas Assessments of Academic Readiness", 
"State of Texas Assessments of Academic Readiness", "State of Texas Assessments of Academic Readiness", 
"State of Texas Assessments of Academic Readiness"),
  `exam_sort` = c(2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 
3, 3, 3),
  `performance_standard` = c("Met standard or above (source-harmonized)", "Met standard or above (source-harmonized)", 
"Met standard or above (source-harmonized)", "Met standard or above (source-harmonized)", 
"Met standard or above (source-harmonized)", "Met standard or above (source-harmonized)", 
"Met standard or above (source-harmonized)", "Met standard or above (source-harmonized)", 
"Met standard or above (source-harmonized)", "Satisfactory", 
"Satisfactory", "Satisfactory", "Satisfactory", "Satisfactory", 
"Approaches and Above", "Approaches and Above", "Approaches and Above", 
"Approaches and Above", "Approaches and Above", "Approaches and Above", 
"Approaches and Above", "Approaches and Above", "Approaches and Above"
),
  `tests_passed` = c(NA, NA, NA, NA, NA, NA, NA, NA, NA, 1560, 1738, 1771, 1625, 
1747, 1775, 1800, 1973, 1596, 1869, 1802, 1630, 1712, 1632),
  `tests_taken` = c(NA, NA, NA, NA, NA, NA, NA, NA, NA, 1899, 2096, 2136, 2104, 
2172, 2228, 2269, 2415, 2046, 2390, 2319, 2273, 2295, 2162),
  `grades_included` = c("District-reported tested grades", "District-reported tested grades", 
"District-reported tested grades", "District-reported tested grades", 
"District-reported tested grades", "District-reported tested grades", 
"District-reported tested grades", "District-reported tested grades", 
"District-reported tested grades", "5,8", "5,8", "5,8", "5,8", 
"5,8", "5,8", "5,8", "5,8", "5,8", "5,8", "5,8", "5,8", "5,8", 
"5,8"),
  `grade_count` = c(NA, NA, NA, NA, NA, NA, NA, NA, NA, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2),
  `calculation_method` = c("reported_district_subject_proportion", "reported_district_subject_proportion", 
"reported_district_subject_proportion", "reported_district_subject_proportion", 
"reported_district_subject_proportion", "reported_district_subject_proportion", 
"reported_district_subject_proportion", "reported_district_subject_proportion", 
"reported_district_subject_proportion", "ratio_of_sums_tests_passed_divided_by_tests_taken", 
"ratio_of_sums_tests_passed_divided_by_tests_taken", "ratio_of_sums_tests_passed_divided_by_tests_taken", 
"ratio_of_sums_tests_passed_divided_by_tests_taken", "ratio_of_sums_tests_passed_divided_by_tests_taken", 
"ratio_of_sums_tests_passed_divided_by_tests_taken", "ratio_of_sums_tests_passed_divided_by_tests_taken", 
"ratio_of_sums_tests_passed_divided_by_tests_taken", "ratio_of_sums_tests_passed_divided_by_tests_taken", 
"ratio_of_sums_tests_passed_divided_by_tests_taken", "ratio_of_sums_tests_passed_divided_by_tests_taken", 
"ratio_of_sums_tests_passed_divided_by_tests_taken", "ratio_of_sums_tests_passed_divided_by_tests_taken", 
"ratio_of_sums_tests_passed_divided_by_tests_taken"),
  `series_type` = c("reported", "reported", "reported", "reported", "reported", 
"reported", "reported", "reported", "reported", "derived_from_counts", 
"derived_from_counts", "derived_from_counts", "derived_from_counts", 
"derived_from_counts", "derived_from_counts", "derived_from_counts", 
"derived_from_counts", "derived_from_counts", "derived_from_counts", 
"derived_from_counts", "derived_from_counts", "derived_from_counts", 
"derived_from_counts"),
  `reporting_status` = c("reported", "reported", "reported", "reported", "reported", 
"reported", "reported", "reported", "reported", "reported_or_derived", 
"reported_or_derived", "reported_or_derived", "reported_or_derived", 
"reported_or_derived", "reported_or_derived", "reported_or_derived", 
"reported_or_derived", "reported_or_derived", "reported_or_derived", 
"reported_or_derived", "reported_or_derived", "reported_or_derived", 
"reported_or_derived"),
  `unit` = c("proportion", "proportion", "proportion", "proportion", "proportion", 
"proportion", "proportion", "proportion", "proportion", "proportion", 
"proportion", "proportion", "proportion", "proportion", "proportion", 
"proportion", "proportion", "proportion", "proportion", "proportion", 
"proportion", "proportion", "proportion"),
  `direction` = c("higher_is_better", "higher_is_better", "higher_is_better", 
"higher_is_better", "higher_is_better", "higher_is_better", "higher_is_better", 
"higher_is_better", "higher_is_better", "higher_is_better", "higher_is_better", 
"higher_is_better", "higher_is_better", "higher_is_better", "higher_is_better", 
"higher_is_better", "higher_is_better", "higher_is_better", "higher_is_better", 
"higher_is_better", "higher_is_better", "higher_is_better", "higher_is_better"
),
  `district_id` = c("094902", "094902", "094902", "094902", "094902", "094902", 
"094902", "094902", "094902", "094902", "094902", "094902", "094902", 
"094902", "094902", "094902", "094902", "094902", "094902", "094902", 
"094902", "094902", "094902"),
  `organization_name` = c("Schertz-Cibolo-Universal City ISD", "Schertz-Cibolo-Universal City ISD", 
"Schertz-Cibolo-Universal City ISD", "Schertz-Cibolo-Universal City ISD", 
"Schertz-Cibolo-Universal City ISD", "Schertz-Cibolo-Universal City ISD", 
"Schertz-Cibolo-Universal City ISD", "Schertz-Cibolo-Universal City ISD", 
"Schertz-Cibolo-Universal City ISD", "Schertz-Cibolo-Universal City ISD", 
"Schertz-Cibolo-Universal City ISD", "Schertz-Cibolo-Universal City ISD", 
"Schertz-Cibolo-Universal City ISD", "Schertz-Cibolo-Universal City ISD", 
"Schertz-Cibolo-Universal City ISD", "Schertz-Cibolo-Universal City ISD", 
"Schertz-Cibolo-Universal City ISD", "Schertz-Cibolo-Universal City ISD", 
"Schertz-Cibolo-Universal City ISD", "Schertz-Cibolo-Universal City ISD", 
"Schertz-Cibolo-Universal City ISD", "Schertz-Cibolo-Universal City ISD", 
"Schertz-Cibolo-Universal City ISD"),
  `source_file` = c("SCUC_Snapshots_1995_to_2023_LONG_CANONICAL.csv", "SCUC_Snapshots_1995_to_2023_LONG_CANONICAL.csv", 
"SCUC_Snapshots_1995_to_2023_LONG_CANONICAL.csv", "SCUC_Snapshots_1995_to_2023_LONG_CANONICAL.csv", 
"SCUC_Snapshots_1995_to_2023_LONG_CANONICAL.csv", "SCUC_Snapshots_1995_to_2023_LONG_CANONICAL.csv", 
"SCUC_Snapshots_1995_to_2023_LONG_CANONICAL.csv", "SCUC_Snapshots_1995_to_2023_LONG_CANONICAL.csv", 
"SCUC_Snapshots_1995_to_2023_LONG_CANONICAL.csv", "SCUC_STAAR_Grades_3_8_Annual_2012_2026_LONG_CANONICAL.csv", 
"SCUC_STAAR_Grades_3_8_Annual_2012_2026_LONG_CANONICAL.csv", 
"SCUC_STAAR_Grades_3_8_Annual_2012_2026_LONG_CANONICAL.csv", 
"SCUC_STAAR_Grades_3_8_Annual_2012_2026_LONG_CANONICAL.csv", 
"SCUC_STAAR_Grades_3_8_Annual_2012_2026_LONG_CANONICAL.csv", 
"SCUC_STAAR_Grades_3_8_Annual_2012_2026_LONG_CANONICAL.csv", 
"SCUC_STAAR_Grades_3_8_Annual_2012_2026_LONG_CANONICAL.csv", 
"SCUC_STAAR_Grades_3_8_Annual_2012_2026_LONG_CANONICAL.csv", 
"SCUC_STAAR_Grades_3_8_Annual_2012_2026_LONG_CANONICAL.csv", 
"SCUC_STAAR_Grades_3_8_Annual_2012_2026_LONG_CANONICAL.csv", 
"SCUC_STAAR_Grades_3_8_Annual_2012_2026_LONG_CANONICAL.csv", 
"SCUC_STAAR_Grades_3_8_Annual_2012_2026_LONG_CANONICAL.csv", 
"SCUC_STAAR_Grades_3_8_Annual_2012_2026_LONG_CANONICAL.csv", 
"SCUC_STAAR_Grades_3_8_Annual_2012_2026_LONG_CANONICAL.csv"),
  `.plot_group` = structure(c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L), levels = "Science", class = "factor"),
  `.chart_x` = structure(c(12053, 12418, 12784, 13149, 13514, 13879, 14245, 
14610, 14975, 15340, 15706, 16071, 16436, 16801, 17167, 17532, 
17897, 18628, 18993, 19358, 19723, 20089, 20454), class = "Date"),
  `emp_cl_orig` = c(0.828062133216686, 0.828062133216686, 0.828062133216686, 0.828062133216686, 
0.828062133216686, 0.828062133216686, 0.828062133216686, 0.828062133216686, 
0.828062133216686, 0.828062133216686, 0.828062133216686, 0.828062133216686, 
0.828062133216686, 0.828062133216686, 0.828062133216686, 0.828062133216686, 
0.828062133216686, 0.828062133216686, 0.828062133216686, 0.828062133216686, 
0.828062133216686, 0.828062133216686, 0.828062133216686),
  `emp_ucl_orig` = c(0.943261118742624, 0.943261118742624, 0.943261118742624, 0.943261118742624, 
0.943261118742624, 0.943261118742624, 0.943261118742624, 0.943261118742624, 
0.943261118742624, 0.943261118742624, 0.943261118742624, 0.943261118742624, 
0.943261118742624, 0.943261118742624, 0.943261118742624, 0.943261118742624, 
0.943261118742624, 0.943261118742624, 0.943261118742624, 0.943261118742624, 
0.943261118742624, 0.943261118742624, 0.943261118742624),
  `emp_lcl_orig` = c(0.712863147690749, 0.712863147690749, 0.712863147690749, 0.712863147690749, 
0.712863147690749, 0.712863147690749, 0.712863147690749, 0.712863147690749, 
0.712863147690749, 0.712863147690749, 0.712863147690749, 0.712863147690749, 
0.712863147690749, 0.712863147690749, 0.712863147690749, 0.712863147690749, 
0.712863147690749, 0.712863147690749, 0.712863147690749, 0.712863147690749, 
0.712863147690749, 0.712863147690749, 0.712863147690749),
  `emp_cl_recalc` = c(0.780817424373522, 0.780817424373522, 0.780817424373522, 0.780817424373522, 
0.780817424373522, 0.780817424373522, 0.780817424373522, 0.780817424373522, 
0.780817424373522, 0.780817424373522, 0.780817424373522, 0.780817424373522, 
0.780817424373522, 0.780817424373522, 0.780817424373522, 0.780817424373522, 
0.780817424373522, 0.780817424373522, 0.780817424373522, 0.780817424373522, 
0.780817424373522, 0.780817424373522, 0.780817424373522),
  `emp_ucl_recalc` = c(0.860507368572773, 0.860507368572773, 0.860507368572773, 0.860507368572773, 
0.860507368572773, 0.860507368572773, 0.860507368572773, 0.860507368572773, 
0.860507368572773, 0.860507368572773, 0.860507368572773, 0.860507368572773, 
0.860507368572773, 0.860507368572773, 0.860507368572773, 0.860507368572773, 
0.860507368572773, 0.860507368572773, 0.860507368572773, 0.860507368572773, 
0.860507368572773, 0.860507368572773, 0.860507368572773),
  `emp_lcl_recalc` = c(0.701127480174271, 0.701127480174271, 0.701127480174271, 0.701127480174271, 
0.701127480174271, 0.701127480174271, 0.701127480174271, 0.701127480174271, 
0.701127480174271, 0.701127480174271, 0.701127480174271, 0.701127480174271, 
0.701127480174271, 0.701127480174271, 0.701127480174271, 0.701127480174271, 
0.701127480174271, 0.701127480174271, 0.701127480174271, 0.701127480174271, 
0.701127480174271, 0.701127480174271, 0.701127480174271),
  `recalc_date` = structure(c(15924, 15924, 15924, 15924, 15924, 15924, 15924, 
15924, 15924, 15924, 15924, 15924, 15924, 15924, 15924, 15924, 
15924, 15924, 15924, 15924, 15924, 15924, 15924), class = "Date"),
  `sigma_signals` = c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
FALSE, FALSE, FALSE, FALSE, FALSE),
  `same_side_signal` = c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
FALSE, FALSE, FALSE, FALSE, FALSE),
  `trend_signal` = c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
FALSE, FALSE, FALSE, FALSE, FALSE),
  `alternating_signal` = c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
FALSE, FALSE, FALSE, FALSE, FALSE),
  `runs_signal` = c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
FALSE, FALSE, FALSE, FALSE, FALSE)
,
  check.names = FALSE
)

# The limit and signal columns below are the values calculated by Policycraft.
chart <- ggplot(chart_data, aes(x = `date`, y = value, group = `.plot_group`))
chart <- chart + geom_line(colour = "darkgray", linewidth = 1.2)
chart <- chart + geom_point(aes(colour = sigma_signals), size = 2.5)
chart <- chart + did_it_work_subject_end_layer(chart_data)
chart <- chart + geom_line(aes(y = ifelse(`.chart_x` < recalc_date, emp_cl_orig, NA)), colour = "blue")
chart <- chart + geom_line(aes(y = ifelse(`.chart_x` >= recalc_date, emp_cl_recalc, NA)), colour = "green")
chart <- chart + geom_line(aes(y = ifelse(`.chart_x` < recalc_date, emp_ucl_orig, NA)), colour = "red")
chart <- chart + geom_line(aes(y = ifelse(`.chart_x` < recalc_date, emp_lcl_orig, NA)), colour = "red")
chart <- chart + geom_line(aes(y = ifelse(`.chart_x` >= recalc_date, emp_ucl_recalc, NA)), colour = "red", linetype = "dashed")
chart <- chart + geom_line(aes(y = ifelse(`.chart_x` >= recalc_date, emp_lcl_recalc, NA)), colour = "red", linetype = "dashed")
chart <- chart + geom_vline(xintercept = unique(chart_data$recalc_date), colour = "purple", linetype = "dotted")
chart <- chart + annotate("text", x = min(chart_data$`date`), y = chart_data$emp_cl_orig[1], label = paste0("Original CL (", round(chart_data$emp_cl_orig[1], 2), ")"), colour = "blue", size = 4.8, fontface = "bold", hjust = 0, vjust = -0.8)
chart <- chart + annotate("text", x = unique(chart_data$recalc_date), y = chart_data$emp_cl_recalc[1], label = paste0("Recalculated CL (", round(chart_data$emp_cl_recalc[1], 2), ")"), colour = "green4", size = 4.8, fontface = "bold", hjust = 0, vjust = -0.8)
chart <- chart + annotate("text", x = min(chart_data$`date`), y = chart_data$emp_ucl_orig[1], label = paste0("Original UCL (", round(chart_data$emp_ucl_orig[1], 2), ")"), colour = "red", size = 4.6, fontface = "bold", hjust = 0, vjust = -0.6)
chart <- chart + annotate("text", x = min(chart_data$`date`), y = chart_data$emp_lcl_orig[1], label = paste0("Original LCL (", round(chart_data$emp_lcl_orig[1], 2), ")"), colour = "red", size = 4.6, fontface = "bold", hjust = 0, vjust = 1.4)
chart <- chart + annotate("text", x = unique(chart_data$recalc_date), y = chart_data$emp_ucl_recalc[1], label = paste0("Recalculated UCL (", round(chart_data$emp_ucl_recalc[1], 2), ")"), colour = "red", size = 4.6, fontface = "bold", hjust = 0, vjust = -0.6)
chart <- chart + annotate("text", x = unique(chart_data$recalc_date), y = chart_data$emp_lcl_recalc[1], label = paste0("Recalculated LCL (", round(chart_data$emp_lcl_recalc[1], 2), ")"), colour = "red", size = 4.6, fontface = "bold", hjust = 0, vjust = 1.4)
chart <- chart + did_it_work_superintendent_layers(chart_data$date)
chart <- chart + scale_colour_manual(values = c(`TRUE` = "red", `FALSE` = "blue"))

# Match the graduations used in the Policycraft app.
date_span <- as.numeric(diff(range(chart_data$date, na.rm = TRUE)))
date_breaks <- if (date_span > 1825) "1 year" else if (date_span > 365) "6 months" else if (date_span > 90) "1 month" else "1 week"
date_labels <- if (all(format(chart_data$date, "%m-%d") == "01-01")) "%Y" else "%Y-%m-%d"
chart <- chart + scale_x_date(date_breaks = date_breaks, date_labels = date_labels, expand = expansion(mult = c(0.05, 0.18)))
chart <- chart + did_it_work_percent_scale()

chart <- chart + ggplot2::labs(
    title = "Title",
    subtitle = "Subtitle",
    caption = "Caption",
    x = "Academic Year Ended",
    y = "Pct Meeting Standard"
  )
chart <- chart + did_it_work_chart_theme()

if (interactive()) print(chart)

save_did_it_work_chart(
  chart,
  "ggplot2 code/science_expectation_chart_2026-09-11-landscape.png"
)
