# Readable ggplot2 code generated by policycraft
library(ggplot2)
library(dplyr)
source(file.path("ggplot2 code", "did_it_work_chart_helpers.R"))

chart_data <- data.frame(
  `date` = structure(c(9131, 9496, 9862, 10227, 10592, 10957, 11323, 11688,
12053, 12418, 12784, 13149, 13514, 13879, 14245, 14610, 14975,
15340, 15706, 16071, 16436, 16801, 17167, 17532, 17897, 18628
), class = "Date"),
  `value` = c(0.817, 0.802, 0.839, 0.809, 0.849, 0.88, 0.866, 0.903, 0.826,
0.95, 0.91, 0.92, 0.94, 0.94, 0.95, 0.93, 0.92, 0.766970618034448,
0.756611165523996, 0.762, 0.758817921830315, 0.73489932885906,
0.7103726986978, 0.720981165133596, 0.703898379325449, 0.625834127740705
),
  `Year` = c(1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004,
2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015,
2016, 2017, 2018, 2019, 2021),
  `academic_year` = c("1994-1995", "1995-1996", "1996-1997", "1997-1998", "1998-1999",
"1999-2000", "2000-2001", "2001-2002", "2002-2003", "2003-2004",
"2004-2005", "2005-2006", "2006-2007", "2007-2008", "2008-2009",
"2009-2010", "2010-2011", "2011-2012", "2012-2013", "2013-2014",
"2014-2015", "2015-2016", "2016-2017", "2017-2018", "2018-2019",
"2020-2021"),
  `percent` = c(81.7, 80.2, 83.9, 80.9, 84.9, 88, 86.6, 90.3, 82.6, 95, 91,
92, 94, 94, 95, 93, 92, 76.6970618034448, 75.6611165523996, 76.2,
75.8817921830315, 73.489932885906, 71.03726986978, 72.0981165133596,
70.3898379325449, 62.5834127740705),
  `series_label` = c("Writing", "Writing", "Writing", "Writing", "Writing", "Writing",
"Writing", "Writing", "Writing", "Writing", "Writing", "Writing",
"Writing", "Writing", "Writing", "Writing", "Writing", "Writing",
"Writing", "Writing", "Writing", "Writing", "Writing", "Writing",
"Writing", "Writing"),
  `subject` = c("Writing", "Writing", "Writing", "Writing", "Writing", "Writing",
"Writing", "Writing", "Writing", "Writing", "Writing", "Writing",
"Writing", "Writing", "Writing", "Writing", "Writing", "Writing",
"Writing", "Writing", "Writing", "Writing", "Writing", "Writing",
"Writing", "Writing"),
  `subject_sort` = c(2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
2, 2, 2, 2, 2, 2),
  `exam_type` = c("TAAS", "TAAS", "TAAS", "TAAS", "TAAS", "TAAS", "TAAS", "TAAS",
"TAKS", "TAKS", "TAKS", "TAKS", "TAKS", "TAKS", "TAKS", "TAKS",
"TAKS", "STAAR", "STAAR", "STAAR", "STAAR", "STAAR", "STAAR",
"STAAR", "STAAR", "STAAR"),
  `exam_name` = c("Texas Assessment of Academic Skills", "Texas Assessment of Academic Skills",
"Texas Assessment of Academic Skills", "Texas Assessment of Academic Skills",
"Texas Assessment of Academic Skills", "Texas Assessment of Academic Skills",
"Texas Assessment of Academic Skills", "Texas Assessment of Academic Skills",
"Texas Assessment of Knowledge and Skills", "Texas Assessment of Knowledge and Skills",
"Texas Assessment of Knowledge and Skills", "Texas Assessment of Knowledge and Skills",
"Texas Assessment of Knowledge and Skills", "Texas Assessment of Knowledge and Skills",
"Texas Assessment of Knowledge and Skills", "Texas Assessment of Knowledge and Skills",
"Texas Assessment of Knowledge and Skills", "State of Texas Assessments of Academic Readiness",
"State of Texas Assessments of Academic Readiness", "State of Texas Assessments of Academic Readiness",
"State of Texas Assessments of Academic Readiness", "State of Texas Assessments of Academic Readiness",
"State of Texas Assessments of Academic Readiness", "State of Texas Assessments of Academic Readiness",
"State of Texas Assessments of Academic Readiness", "State of Texas Assessments of Academic Readiness"
),
  `exam_sort` = c(1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3,
3, 3, 3, 3, 3, 3),
  `performance_standard` = c("Met standard or above (source-harmonized)", "Met standard or above (source-harmonized)",
"Met standard or above (source-harmonized)", "Met standard or above (source-harmonized)",
"Met standard or above (source-harmonized)", "Met standard or above (source-harmonized)",
"Met standard or above (source-harmonized)", "Met standard or above (source-harmonized)",
"Met standard or above (source-harmonized)", "Met standard or above (source-harmonized)",
"Met standard or above (source-harmonized)", "Met standard or above (source-harmonized)",
"Met standard or above (source-harmonized)", "Met standard or above (source-harmonized)",
"Met standard or above (source-harmonized)", "Met standard or above (source-harmonized)",
"Met standard or above (source-harmonized)", "Satisfactory",
"Satisfactory", "Satisfactory", "Satisfactory", "Satisfactory",
"Approaches and Above", "Approaches and Above", "Approaches and Above",
"Approaches and Above"),
  `tests_passed` = c(NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
NA, NA, 1514, 1545, 1524, 1592, 1533, 1582, 1646, 1607, 1313),
  `tests_taken` = c(NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
NA, NA, 1974, 2042, 2000, 2098, 2086, 2227, 2283, 2283, 2098),
  `grades_included` = c("District-reported tested grades", "District-reported tested grades",
"District-reported tested grades", "District-reported tested grades",
"District-reported tested grades", "District-reported tested grades",
"District-reported tested grades", "District-reported tested grades",
"District-reported tested grades", "District-reported tested grades",
"District-reported tested grades", "District-reported tested grades",
"District-reported tested grades", "District-reported tested grades",
"District-reported tested grades", "District-reported tested grades",
"District-reported tested grades", "4,7", "4,7", "4,7", "4,7",
"4,7", "4,7", "4,7", "4,7", "4,7"),
  `grade_count` = c(NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
NA, NA, 2, 2, 2, 2, 2, 2, 2, 2, 2),
  `calculation_method` = c("reported_district_subject_proportion", "reported_district_subject_proportion",
"reported_district_subject_proportion", "reported_district_subject_proportion",
"reported_district_subject_proportion", "reported_district_subject_proportion",
"reported_district_subject_proportion", "reported_district_subject_proportion",
"reported_district_subject_proportion", "reported_district_subject_proportion",
"reported_district_subject_proportion", "reported_district_subject_proportion",
"reported_district_subject_proportion", "reported_district_subject_proportion",
"reported_district_subject_proportion", "reported_district_subject_proportion",
"reported_district_subject_proportion", "ratio_of_sums_tests_passed_divided_by_tests_taken",
"ratio_of_sums_tests_passed_divided_by_tests_taken", "ratio_of_sums_tests_passed_divided_by_tests_taken",
"ratio_of_sums_tests_passed_divided_by_tests_taken", "ratio_of_sums_tests_passed_divided_by_tests_taken",
"ratio_of_sums_tests_passed_divided_by_tests_taken", "ratio_of_sums_tests_passed_divided_by_tests_taken",
"ratio_of_sums_tests_passed_divided_by_tests_taken", "ratio_of_sums_tests_passed_divided_by_tests_taken"
),
  `series_type` = c("reported", "reported", "reported", "reported", "reported",
"reported", "reported", "reported", "reported", "reported", "reported",
"reported", "reported", "reported", "reported", "reported", "reported",
"derived_from_counts", "derived_from_counts", "derived_from_counts",
"derived_from_counts", "derived_from_counts", "derived_from_counts",
"derived_from_counts", "derived_from_counts", "derived_from_counts"
),
  `reporting_status` = c("reported", "reported", "reported", "reported", "reported",
"reported", "reported", "reported", "reported", "reported", "reported",
"reported", "reported", "reported", "reported", "reported", "reported",
"reported_or_derived", "reported_or_derived", "reported_or_derived",
"reported_or_derived", "reported_or_derived", "reported_or_derived",
"reported_or_derived", "reported_or_derived", "reported_or_derived"
),
  `unit` = c("proportion", "proportion", "proportion", "proportion", "proportion",
"proportion", "proportion", "proportion", "proportion", "proportion",
"proportion", "proportion", "proportion", "proportion", "proportion",
"proportion", "proportion", "proportion", "proportion", "proportion",
"proportion", "proportion", "proportion", "proportion", "proportion",
"proportion"),
  `direction` = c("higher_is_better", "higher_is_better", "higher_is_better",
"higher_is_better", "higher_is_better", "higher_is_better", "higher_is_better",
"higher_is_better", "higher_is_better", "higher_is_better", "higher_is_better",
"higher_is_better", "higher_is_better", "higher_is_better", "higher_is_better",
"higher_is_better", "higher_is_better", "higher_is_better", "higher_is_better",
"higher_is_better", "higher_is_better", "higher_is_better", "higher_is_better",
"higher_is_better", "higher_is_better", "higher_is_better"),
  `district_id` = c("094902", "094902", "094902", "094902", "094902", "094902",
"094902", "094902", "094902", "094902", "094902", "094902", "094902",
"094902", "094902", "094902", "094902", "094902", "094902", "094902",
"094902", "094902", "094902", "094902", "094902", "094902"),
  `organization_name` = c("Schertz-Cibolo-Universal City ISD", "Schertz-Cibolo-Universal City ISD",
"Schertz-Cibolo-Universal City ISD", "Schertz-Cibolo-Universal City ISD",
"Schertz-Cibolo-Universal City ISD", "Schertz-Cibolo-Universal City ISD",
"Schertz-Cibolo-Universal City ISD", "Schertz-Cibolo-Universal City ISD",
"Schertz-Cibolo-Universal City ISD", "Schertz-Cibolo-Universal City ISD",
"Schertz-Cibolo-Universal City ISD", "Schertz-Cibolo-Universal City ISD",
"Schertz-Cibolo-Universal City ISD", "Schertz-Cibolo-Universal City ISD",
"Schertz-Cibolo-Universal City ISD", "Schertz-Cibolo-Universal City ISD",
"Schertz-Cibolo-Universal City ISD", "Schertz-Cibolo-Universal City ISD",
"Schertz-Cibolo-Universal City ISD", "Schertz-Cibolo-Universal City ISD",
"Schertz-Cibolo-Universal City ISD", "Schertz-Cibolo-Universal City ISD",
"Schertz-Cibolo-Universal City ISD", "Schertz-Cibolo-Universal City ISD",
"Schertz-Cibolo-Universal City ISD", "Schertz-Cibolo-Universal City ISD"
),
  `source_file` = c("SCUC_Snapshots_1995_to_2023_LONG_CANONICAL.csv", "SCUC_Snapshots_1995_to_2023_LONG_CANONICAL.csv",
"SCUC_Snapshots_1995_to_2023_LONG_CANONICAL.csv", "SCUC_Snapshots_1995_to_2023_LONG_CANONICAL.csv",
"SCUC_Snapshots_1995_to_2023_LONG_CANONICAL.csv", "SCUC_Snapshots_1995_to_2023_LONG_CANONICAL.csv",
"SCUC_Snapshots_1995_to_2023_LONG_CANONICAL.csv", "SCUC_Snapshots_1995_to_2023_LONG_CANONICAL.csv",
"SCUC_Snapshots_1995_to_2023_LONG_CANONICAL.csv", "SCUC_Snapshots_1995_to_2023_LONG_CANONICAL.csv",
"SCUC_Snapshots_1995_to_2023_LONG_CANONICAL.csv", "SCUC_Snapshots_1995_to_2023_LONG_CANONICAL.csv",
"SCUC_Snapshots_1995_to_2023_LONG_CANONICAL.csv", "SCUC_Snapshots_1995_to_2023_LONG_CANONICAL.csv",
"SCUC_Snapshots_1995_to_2023_LONG_CANONICAL.csv", "SCUC_Snapshots_1995_to_2023_LONG_CANONICAL.csv",
"SCUC_Snapshots_1995_to_2023_LONG_CANONICAL.csv", "SCUC_STAAR_Grades_3_8_Annual_2012_2026_LONG_CANONICAL.csv",
"SCUC_STAAR_Grades_3_8_Annual_2012_2026_LONG_CANONICAL.csv",
"SCUC_STAAR_Grades_3_8_Annual_2012_2026_LONG_CANONICAL.csv",
"SCUC_STAAR_Grades_3_8_Annual_2012_2026_LONG_CANONICAL.csv",
"SCUC_STAAR_Grades_3_8_Annual_2012_2026_LONG_CANONICAL.csv",
"SCUC_STAAR_Grades_3_8_Annual_2012_2026_LONG_CANONICAL.csv",
"SCUC_STAAR_Grades_3_8_Annual_2012_2026_LONG_CANONICAL.csv",
"SCUC_STAAR_Grades_3_8_Annual_2012_2026_LONG_CANONICAL.csv",
"SCUC_STAAR_Grades_3_8_Annual_2012_2026_LONG_CANONICAL.csv"),
  `.plot_group` = structure(c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L,
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L), levels = "Writing", class = "factor"),
  `.chart_x` = structure(c(9131, 9496, 9862, 10227, 10592, 10957, 11323, 11688,
12053, 12418, 12784, 13149, 13514, 13879, 14245, 14610, 14975,
15340, 15706, 16071, 16436, 16801, 17167, 17532, 17897, 18628
), class = "Date"),
  `emp_cl_orig` = c(0.872346409660971, 0.872346409660971, 0.872346409660971, 0.872346409660971,
0.872346409660971, 0.872346409660971, 0.872346409660971, 0.872346409660971,
0.872346409660971, 0.872346409660971, 0.872346409660971, 0.872346409660971,
0.872346409660971, 0.872346409660971, 0.872346409660971, 0.872346409660971,
0.872346409660971, 0.872346409660971, 0.872346409660971, 0.872346409660971,
0.872346409660971, 0.872346409660971, 0.872346409660971, 0.872346409660971,
0.872346409660971, 0.872346409660971),
  `emp_ucl_orig` = c(1.05917709529434, 1.05917709529434, 1.05917709529434, 1.05917709529434,
1.05917709529434, 1.05917709529434, 1.05917709529434, 1.05917709529434,
1.05917709529434, 1.05917709529434, 1.05917709529434, 1.05917709529434,
1.05917709529434, 1.05917709529434, 1.05917709529434, 1.05917709529434,
1.05917709529434, 1.05917709529434, 1.05917709529434, 1.05917709529434,
1.05917709529434, 1.05917709529434, 1.05917709529434, 1.05917709529434,
1.05917709529434, 1.05917709529434),
  `emp_lcl_orig` = c(0.6855157240276, 0.6855157240276, 0.6855157240276, 0.6855157240276,
0.6855157240276, 0.6855157240276, 0.6855157240276, 0.6855157240276,
0.6855157240276, 0.6855157240276, 0.6855157240276, 0.6855157240276,
0.6855157240276, 0.6855157240276, 0.6855157240276, 0.6855157240276,
0.6855157240276, 0.6855157240276, 0.6855157240276, 0.6855157240276,
0.6855157240276, 0.6855157240276, 0.6855157240276, 0.6855157240276,
0.6855157240276, 0.6855157240276),
  `emp_cl_recalc` = c(0.716686231655275, 0.716686231655275, 0.716686231655275, 0.716686231655275,
0.716686231655275, 0.716686231655275, 0.716686231655275, 0.716686231655275,
0.716686231655275, 0.716686231655275, 0.716686231655275, 0.716686231655275,
0.716686231655275, 0.716686231655275, 0.716686231655275, 0.716686231655275,
0.716686231655275, 0.716686231655275, 0.716686231655275, 0.716686231655275,
0.716686231655275, 0.716686231655275, 0.716686231655275, 0.716686231655275,
0.716686231655275, 0.716686231655275),
  `emp_ucl_recalc` = c(0.846717576048872, 0.846717576048872, 0.846717576048872, 0.846717576048872,
0.846717576048872, 0.846717576048872, 0.846717576048872, 0.846717576048872,
0.846717576048872, 0.846717576048872, 0.846717576048872, 0.846717576048872,
0.846717576048872, 0.846717576048872, 0.846717576048872, 0.846717576048872,
0.846717576048872, 0.846717576048872, 0.846717576048872, 0.846717576048872,
0.846717576048872, 0.846717576048872, 0.846717576048872, 0.846717576048872,
0.846717576048872, 0.846717576048872),
  `emp_lcl_recalc` = c(0.586654887261678, 0.586654887261678, 0.586654887261678, 0.586654887261678,
0.586654887261678, 0.586654887261678, 0.586654887261678, 0.586654887261678,
0.586654887261678, 0.586654887261678, 0.586654887261678, 0.586654887261678,
0.586654887261678, 0.586654887261678, 0.586654887261678, 0.586654887261678,
0.586654887261678, 0.586654887261678, 0.586654887261678, 0.586654887261678,
0.586654887261678, 0.586654887261678, 0.586654887261678, 0.586654887261678,
0.586654887261678, 0.586654887261678),
  `recalc_date` = structure(c(15924, 15924, 15924, 15924, 15924, 15924, 15924,
15924, 15924, 15924, 15924, 15924, 15924, 15924, 15924, 15924,
15924, 15924, 15924, 15924, 15924, 15924, 15924, 15924, 15924,
15924), class = "Date"),
  `sigma_signals` = c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE,
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE,
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
  `same_side_signal` = c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE,
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE,
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
  `trend_signal` = c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE,
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE,
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
  `alternating_signal` = c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE,
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE,
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
  `runs_signal` = c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE,
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE,
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE)
,
  check.names = FALSE
)

# The limit and signal columns below are the values calculated by Policycraft.
chart <- ggplot(chart_data, aes(x = `date`, y = value, group = `.plot_group`))
chart <- chart + geom_line(colour = "darkgray", linewidth = 1.2)
chart <- chart + geom_point(aes(colour = sigma_signals), size = 2.5)
chart <- chart + did_it_work_subject_end_layer(chart_data)
chart <- chart + geom_line(aes(y = ifelse(`.chart_x` < recalc_date, emp_cl_orig, NA)), colour = "blue")
chart <- chart + geom_line(aes(y = ifelse(`.chart_x` >= recalc_date, emp_cl_recalc, NA)), colour = "green")
chart <- chart + geom_line(aes(y = ifelse(`.chart_x` < recalc_date, emp_ucl_orig, NA)), colour = "red")
chart <- chart + geom_line(aes(y = ifelse(`.chart_x` < recalc_date, emp_lcl_orig, NA)), colour = "red")
chart <- chart + geom_line(aes(y = ifelse(`.chart_x` >= recalc_date, emp_ucl_recalc, NA)), colour = "red", linetype = "dashed")
chart <- chart + geom_line(aes(y = ifelse(`.chart_x` >= recalc_date, emp_lcl_recalc, NA)), colour = "red", linetype = "dashed")
chart <- chart + geom_vline(xintercept = unique(chart_data$recalc_date), colour = "purple", linetype = "dotted")
chart <- chart + annotate("text", x = min(chart_data$`date`), y = chart_data$emp_cl_orig[1], label = paste0("Original CL (", round(chart_data$emp_cl_orig[1], 2), ")"), colour = "blue", size = 4.8, fontface = "bold", hjust = 0, vjust = -0.8)
chart <- chart + annotate("text", x = unique(chart_data$recalc_date), y = chart_data$emp_cl_recalc[1], label = paste0("Recalculated CL (", round(chart_data$emp_cl_recalc[1], 2), ")"), colour = "green4", size = 4.8, fontface = "bold", hjust = 0, vjust = -0.8)
chart <- chart + annotate("text", x = min(chart_data$`date`), y = chart_data$emp_ucl_orig[1], label = paste0("Original UCL (", round(chart_data$emp_ucl_orig[1], 2), ")"), colour = "red", size = 4.6, fontface = "bold", hjust = 0, vjust = -0.6)
chart <- chart + annotate("text", x = min(chart_data$`date`), y = chart_data$emp_lcl_orig[1], label = paste0("Original LCL (", round(chart_data$emp_lcl_orig[1], 2), ")"), colour = "red", size = 4.6, fontface = "bold", hjust = 0, vjust = 1.4)
chart <- chart + annotate("text", x = unique(chart_data$recalc_date), y = chart_data$emp_ucl_recalc[1], label = paste0("Recalculated UCL (", round(chart_data$emp_ucl_recalc[1], 2), ")"), colour = "red", size = 4.6, fontface = "bold", hjust = 0, vjust = -0.6)
chart <- chart + annotate("text", x = unique(chart_data$recalc_date), y = chart_data$emp_lcl_recalc[1], label = paste0("Recalculated LCL (", round(chart_data$emp_lcl_recalc[1], 2), ")"), colour = "red", size = 4.6, fontface = "bold", hjust = 0, vjust = 1.4)
chart <- chart + did_it_work_superintendent_layers(chart_data$date)
chart <- chart + scale_colour_manual(values = c(`TRUE` = "red", `FALSE` = "blue"))

# Match the graduations used in the Policycraft app.
date_span <- as.numeric(diff(range(chart_data$date, na.rm = TRUE)))
date_breaks <- if (date_span > 1825) "1 year" else if (date_span > 365) "6 months" else if (date_span > 90) "1 month" else "1 week"
date_labels <- if (all(format(chart_data$date, "%m-%d") == "01-01")) "%Y" else "%Y-%m-%d"
chart <- chart + scale_x_date(date_breaks = date_breaks, date_labels = date_labels, expand = expansion(mult = c(0.05, 0.18)))
chart <- chart + did_it_work_percent_scale()

chart <- chart + ggplot2::labs(
  title = "None of The Initiatives Over All Those Years Worked. We Are Doing Worse Now Than 1995",
  subtitle = "(Baldridge, MAP, DEI, Mission-Vision-Values, Closing the Gaps, TASB Good Governance, etc. etc. etc)",
  caption = "Data Source:  TEA Website",
  x = "Year After Year - Initiative After Initiative",
  y = "Pct Meeting Standard"
  )
chart <- chart + did_it_work_chart_theme()

if (interactive()) print(chart)

# Save in a widescreen landscape layout. Keeping these dimensions here makes
# the intended orientation reproducible when this script is run directly.
ggsave(
  filename = "img/writing_did_it_work_chart_2026-09-11-landscape.png",
  plot = chart,
  width = 16,
  height = 9,
  units = "in",
  dpi = 300,
  bg = "white"
)
